console.log("Olá Mundo")
console.log("Estou começando a minha jornada em dados e IA")
console.log(2**64)
console.log("Dados")
console.log("Machine learning")
console.log("Inteligencia Artificial")
console.log("Meu nome é Pedro")
console.log("Eu tenho 11 anos")
console.log("E eu estou aprendendo JavaScript")
console.log("E euquero aprender Machine Learning")
console.log("Um ChatBot que eu ja fiz")
console.log("Um jogo com uma IA para jogar contra você")
console.log("Um Chat Bot mais avançado")